version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: gamemanagement-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong_Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - gamemanagement-network
    restart: always

  gamemanagement-api:
    image: gamemanagement-api
    container_name: gamemanagement-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=GameManagementDB;User=sa;Password=Strong_Password123!;TrustServerCertificate=True;MultipleActiveResultSets=true;Connection Timeout=30;
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - gamemanagement-network
    depends_on:
      - sql-server
    restart: on-failure

networks:
  gamemanagement-network:
    driver: bridge

volumes:
  sqlserver-data: 