version: '3.8'

services:
  gamemanagement-api:
    image: gamemanagement-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=GameManagementDB;User=sa;Password=Strong_Password123!;TrustServerCertificate=True;
    depends_on:
      - sql-server
    networks:
      - gamemanagement-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong_Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - gamemanagement-network

networks:
  gamemanagement-network:
    driver: bridge

volumes:
  sqlserver-data: 